### PR TITLE
Replace password value in log by *****

### PR DESCRIPTION
**Pull request by ukolovda**
It will write asterisks into log instead of real password value.

### CODE REVIEW

**Comment by drewbug** [comment]
Perhaps it would be better to make this a configurable option?

**Comment by wconrad** [comment]
Thank you for the PR.  This is a good idea.  I don't think it needs to be configurable.

**Comment by wconrad** [comment]
This patch is in version 2.0.1, which I've just released.  Thanks again!

**Comment by drewbug** [comment]
Yeah, on second thought one could of course log the real password themselves in `Driver#authenticate`.

**Pull request merged**
